### ISSUE TITLE
Miscellaneous TODO:

### ISSUE THREAD

**Issue by xPMo** [xPMo/zsh-toggle-command-prefix#1]
- [x] Start check at the end of the word the cursor is on (it may be `sudo`)
- [x] Support automatically removing `sudo` flags e.g.: `-s shell` `-u user`
- [x] (?) Add `zstyle` option to delete to `$CUTBUFFER` for pasting later

It will be hard to suport both of these together, but:

- [x] Detect quoting with `${(z)BUFFER}`
- [ ] ~~Support `$(command substitutions)`~~

**Comment by xPMo** [comment]
C
